repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.2
    hooks:
      - id: ruff-format
      - id: ruff
        args: [--fix]

  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: pyright moal
        language: system
        pass_filenames: false
        types: [python]
